language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update

  # gcc 4.9
  - if [ "$CXX" == "g++" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    fi

  # clang 3.6.0
  - if [ "$CXX" == "clang++" ]; then
      wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
      sudo add-apt-repository --yes ppa:h-rayflood/llvm;
      sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main';
      sudo add-apt-repository --yes 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main';
    fi

  # SDL2
  - curl -O http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar -xzvf SDL2-2.0.3.tar.gz
  - (cd SDL2-2.0.3 && ./configure && make -j5)

install:
  - sudo apt-get update

  # SDL2
  - (cd SDL2-2.0.3 && sudo make install)

  # gcc 4.9
  - if [ "$CXX" = "g++" ]; then
      sudo apt-get install -y g++-4.9;
      export CC="gcc-4.9";
    fi

  # clang 3.6.0
  - if [ "$CXX" == "clang++" ]; then
      sudo apt-get install -y llvm-3.6 llvm-3.6-dev clang-3.6;
      export CC="clang-3.6";
    fi

script:
    - make -j5

notifications:
    irc:
        channels:
          - "irc.freenode.org#gmqcc"
        template:
          - "[%{commit} : %{author}] %{message}"
          - "%{build_url}"
        skip_join: true
